import { useState } from "react";
import GameTableCard from "./GameTableCard.jsx";
import CreateTableModal from "./CreateTableModal.jsx";
import JoinTableModal from "./JoinTableModal.jsx";
import "./LobbyPage.css";

export default function LobbyPage({ session, table, discoveredTable, onCreate, onLookup, onJoin, onRefresh, onStart, onSignOut }) {
  const [createOpen, setCreateOpen] = useState(false); const [joinOpen, setJoinOpen] = useState(false); const [createForm, setCreateForm] = useState({ name: `${session.player.username}'s table`, bet: 100, max: 4 }); const [tableId, setTableId] = useState(""); const [busy, setBusy] = useState(false); const [joining, setJoining] = useState(false);
  const update = (name) => (event) => setCreateForm({ ...createForm, [name]: event.target.value });
  async function create(event) { event.preventDefault(); setBusy(true); try { await onCreate(createForm); setCreateOpen(false); } finally { setBusy(false); } }
  async function lookup(event) { event.preventDefault(); setBusy(true); try { await onLookup(tableId); setJoinOpen(false); } finally { setBusy(false); } }
  async function join(id) { setJoining(true); try { await onJoin(id); } finally { setJoining(false); } }
  const activeTable = table || discoveredTable;
  return <section className="lobby-page" aria-labelledby="lobby-title"><header className="lobby-page__header"><div><p className="type-label">Teen Patti lobby</p><h1 id="lobby-title">Welcome, {session.player.username}</h1><p>Virtual balance <strong>{session.player.coinBalance} coins</strong></p></div><div className="lobby-page__header-actions"><button className="secondary" type="button" onClick={onRefresh}>Refresh</button><button className="text-button" type="button" onClick={onSignOut}>Sign out</button></div></header><div className="lobby-page__game-picker"><button type="button" className="selected">Teen Patti <small>Available</small></button><button type="button" disabled>Poker <small>Coming soon</small></button><button type="button" disabled>Rummy <small>Coming soon</small></button></div><div className="lobby-page__actions"><button className="primary" type="button" onClick={() => setCreateOpen(true)}>Create table</button><button className="secondary" type="button" onClick={() => setJoinOpen(true)}>Join by table ID</button></div><section className="lobby-page__tables" aria-labelledby="tables-title"><div className="lobby-page__tables-heading"><div><p className="type-label">Table update</p><h2 id="tables-title">{table ? "Your Teen Patti table" : "Table details"}</h2></div><span>Real backend data only</span></div>{activeTable ? <GameTableCard table={activeTable} isCurrent={Boolean(table)} joining={joining} onJoin={join} /> : <div className="lobby-page__empty"><span aria-hidden="true">♠</span><h2>Ready for a table?</h2><p>Create a new Teen Patti table or enter a shared table ID to view and join it.</p></div>}</section>{table && table.hostPlayerId === session.player.playerId && <div className="lobby-page__host-action"><button className="primary" type="button" disabled={table.players.length < 2 || busy} onClick={async () => { setBusy(true); try { await onStart(); } finally { setBusy(false); } }}>{busy ? "STARTING" : table.players.length < 2 ? "WAITING FOR PLAYER" : "START GAME"}</button></div>}<CreateTableModal open={createOpen} onClose={() => setCreateOpen(false)} form={createForm} update={update} onSubmit={create} busy={busy} /><JoinTableModal open={joinOpen} onClose={() => setJoinOpen(false)} tableId={tableId} setTableId={setTableId} onLookup={lookup} busy={busy} /></section>;
}
