import { useState } from "react";
import "./CoinBorrowingPanel.css";

export default function CoinBorrowingPanel({ round, session, borrowing, borrow, refreshBorrowing }) {
  const [lenderId, setLenderId] = useState("");
  const [amount, setAmount] = useState("");
  const [busy, setBusy] = useState(false);
  const maximum = Number(round.currentBet) * 5;
  const lenders = (round.players || []).filter((player) => player.status === "ACTIVE" && player.playerId !== session.player.playerId);
  const request = async () => { setBusy(true); try { if (await borrow(`/rounds/${round.roundId}/coin-requests`, { lenderPlayerId: Number(lenderId), amount: Number(amount) }, "Coin request sent.")) { setLenderId(""); setAmount(""); } } finally { setBusy(false); } };
  const respond = async (requestId, action) => { setBusy(true); try { await borrow(`/coin-requests/${requestId}/${action}`, undefined, action === "accept" ? "Coin request accepted. Debt created." : "Coin request rejected."); } finally { setBusy(false); } };
  return <section className="coin-borrowing" aria-label="Coin borrowing"><header><div><p className="type-label">Coin borrowing</p><h2>Request coins</h2></div><button className="text-button" type="button" onClick={() => refreshBorrowing().catch(() => {})} disabled={busy}>Refresh</button></header><p className="coin-borrowing__balance">Available balance: <strong>{session.player.coinBalance} coins</strong></p><div className="coin-borrowing__form"><label>Lender<select value={lenderId} onChange={(event) => setLenderId(event.target.value)} disabled={busy}><option value="">Select player</option>{lenders.map((player) => <option key={player.playerId} value={player.playerId}>{player.username}</option>)}</select></label><label>Amount<input type="number" min="1" max={maximum} value={amount} onChange={(event) => setAmount(event.target.value)} disabled={busy} /></label><button className="secondary" type="button" disabled={busy || !lenderId || !Number.isInteger(Number(amount)) || Number(amount) < 1 || Number(amount) > maximum} onClick={request}>{busy ? "Sending…" : "Request coins"}</button></div><small>Maximum allowed: <strong>{maximum} coins</strong>. The lender must accept before coins transfer.</small>{borrowing?.pendingIncoming?.length > 0 && <div className="coin-borrowing__requests"><h3>Requests waiting for you</h3>{borrowing.pendingIncoming.map((request) => <article key={request.borrowRequestId}><span><strong>{request.borrowerUsername}</strong> requested {request.amount} coins</span><div><button className="primary" type="button" disabled={busy} onClick={() => respond(request.borrowRequestId, "accept")}>Accept</button><button className="secondary" type="button" disabled={busy} onClick={() => respond(request.borrowRequestId, "reject")}>Reject</button></div></article>)}</div>}{borrowing?.pendingOutgoing?.length > 0 && <div className="coin-borrowing__requests"><h3>Your pending requests</h3>{borrowing.pendingOutgoing.map((request) => <p key={request.borrowRequestId}>{request.amount} coins from <strong>{request.lenderUsername}</strong> — pending</p>)}</div>}{borrowing?.outstandingDebts?.length > 0 && <div className="coin-borrowing__debts"><h3>Outstanding debt</h3>{borrowing.outstandingDebts.map((debt) => <p key={debt.debtId}><strong>{debt.lenderUsername}</strong><span>{debt.remainingAmount} coins · {debt.status.replaceAll("_", " ")}</span></p>)}</div>}</section>;
}
