import { useState } from "react";
import "./GameControls.css";

function SideShowModal({ target, onCancel, onConfirm, busy }) {
  if (!target) return null;
  return <div className="side-show-layer" role="presentation"><button className="side-show-layer__backdrop" type="button" aria-label="Cancel Side Show request" onClick={onCancel} /><div className="side-show-modal" role="dialog" aria-modal="true" aria-labelledby="side-show-title"><p className="type-label">Confirm request</p><h2 id="side-show-title">Side Show with {target.username}</h2><p>The server will validate eligibility and resolve the comparison only after they respond.</p><div><button className="secondary" type="button" onClick={onCancel} disabled={busy}>Cancel</button><button className="primary" type="button" onClick={onConfirm} disabled={busy}>{busy ? "Requesting…" : "Request Side Show"}</button></div></div></div>;
}

export default function GameControls({ round, mine, isYourTurn, run, leaveRound }) {
  const [raise, setRaise] = useState(round.currentBet + 1); const [targetId, setTargetId] = useState(""); const [busy, setBusy] = useState(false); const [feedback, setFeedback] = useState(""); const [confirmTarget, setConfirmTarget] = useState(null);
  const active = (round.players || []).filter((player) => player.status === "ACTIVE" && player.playerId !== mine?.playerId); const minimum = Number(round.currentBet) + 1;
  const invoke = async (path, body, message) => { setBusy(true); setFeedback(""); try { if (await run(path, body)) setFeedback(message); } finally { setBusy(false); } };
  const drop = async () => { setBusy(true); setFeedback(""); try { if (await leaveRound()) setFeedback("Player dropped."); } finally { setBusy(false); } };
  const chooseVisibility = mine?.visibility === "PENDING";
  const canBet = isYourTurn && ["BETTING", "FINAL_TWO", "FORCED_SAME"].includes(round.phase);
  const canSideShow = isYourTurn && round.phase === "FINAL_TWO" && active.length > 0;
  const sideShowTarget = active.find((player) => player.playerId === Number(targetId));
  if (round.phase === "SIDE_SHOW_PENDING") {
    const requested = round.pendingSideShowTargetPlayerId === mine?.playerId;
    return <div className="game-controls">{requested ? <><p className="game-controls__feedback">Side Show requested from you.</p><button className="primary" disabled={busy} onClick={() => invoke(`/rounds/${round.roundId}/side-shows/${round.pendingSideShowId}/response`, { response: "ACCEPT" }, "Side Show accepted. Updating table…")}>Accept Side Show</button><button className="secondary" disabled={busy} onClick={() => invoke(`/rounds/${round.roundId}/side-shows/${round.pendingSideShowId}/response`, { response: "REJECT" }, "Side Show rejected. Updating table…")}>Reject Side Show</button></> : <p className="game-controls__feedback">Side Show requested. Waiting for Player…</p>}</div>;
  }
  return <><div className="game-controls" aria-label="Teen Patti actions">{chooseVisibility && <><button className="primary" disabled={busy} onClick={() => invoke(`/rounds/${round.roundId}/visibility`, { choice: "BLIND" }, "Playing Blind.")}>Play Blind</button><button className="secondary" disabled={busy} onClick={() => invoke(`/rounds/${round.roundId}/visibility`, { choice: "SEEN" }, "Cards visible only to you.")}>See Cards</button></>}{mine?.visibility === "BLIND" && !chooseVisibility && <button className="secondary" disabled={busy} onClick={() => invoke(`/rounds/${round.roundId}/see-cards`, undefined, "Cards visible only to you.")}>See My Cards</button>}{canBet && <><button className="primary" disabled={busy} onClick={() => invoke(`/rounds/${round.roundId}/actions`, { action: "SAME" }, "Matched the required bet.")}>Same {round.currentBet}</button>{["BETTING", "FINAL_TWO"].includes(round.phase) && <><label className="game-controls__raise">Raise to<input type="number" min={minimum} value={raise} onChange={(event) => setRaise(event.target.value)} disabled={busy} /><small>Minimum {minimum}</small></label><button className="secondary" disabled={busy || Number(raise) < minimum} onClick={() => invoke(`/rounds/${round.roundId}/actions`, { action: "RAISE", amount: Number(raise) }, "Raise submitted.")}>Raise</button></>}{canSideShow && <><select value={targetId} onChange={(event) => setTargetId(event.target.value)} disabled={busy}><option value="">Choose Side Show player</option>{active.map((player) => <option key={player.playerId} value={player.playerId}>{player.username}</option>)}</select><button className="secondary" disabled={busy || !sideShowTarget} onClick={() => setConfirmTarget(sideShowTarget)}>Side Show</button></>}<button className="text-button" disabled={busy} onClick={drop}>Drop</button></>}{!canBet && !chooseVisibility && mine?.status === "ACTIVE" && <button className="text-button" disabled={busy} onClick={drop}>Drop</button>}{feedback && <p className="game-controls__feedback" aria-live="polite">{feedback}</p>}</div><SideShowModal target={confirmTarget} busy={busy} onCancel={() => setConfirmTarget(null)} onConfirm={async () => { await invoke(`/rounds/${round.roundId}/side-shows`, { targetPlayerId: confirmTarget.playerId }, "Side Show requested. Waiting for Player…"); setConfirmTarget(null); }} /></>;
}
