import { Client } from "@stomp/stompjs";
import { useCallback, useEffect, useState } from "react";

const API = (import.meta.env.VITE_API_BASE_URL || "/api").replace(/\/$/, "");
const SUITS = { S: "S", H: "H", C: "C", D: "D" };

function auth(credentials) { return `Basic ${btoa(`${credentials.username}:${credentials.password}`)}`; }
function wsUrl() { if (import.meta.env.VITE_WS_URL) return import.meta.env.VITE_WS_URL; return `${location.protocol === "https:" ? "wss" : "ws"}://${location.hostname}:8080/ws`; }
async function api(path, credentials, method = "GET", body) {
  const headers = { Accept: "application/json" }; if (credentials) headers.Authorization = auth(credentials); if (body !== undefined) headers["Content-Type"] = "application/json";
  const response = await fetch(`${API}${path}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.message || `Request failed (${response.status})`); return payload;
}
function Card({ card, hidden }) { return <div className={`card ${hidden ? "card-back" : ["H", "D"].includes(card.suit) ? "red" : ""}`}>{hidden ? "?" : <><span>{card.rank === "T" ? "10" : card.rank}</span><strong>{SUITS[card.suit]}</strong></>}</div>; }
function Message({ error, notice }) { return (error || notice) && <div className={`message ${error ? "error" : "notice"}`}>{error || notice}</div>; }

function Auth({ setSession, tell }) {
  const [register, setRegister] = useState(false); const [form, setForm] = useState({ username: "", email: "", password: "" }); const [busy, setBusy] = useState(false);
  const update = (name) => (event) => setForm({ ...form, [name]: event.target.value });
  async function submit(event) {
    event.preventDefault(); setBusy(true);
    try {
      const credentials = { username: form.username.trim(), password: form.password }; let player;
      if (register) player = await api("/players", null, "POST", { ...form, username: credentials.username });
      else { const id = sessionStorage.getItem(`aceverse:${credentials.username}`); if (!id) throw new Error("Register this player in this browser before signing in."); player = await api(`/players/${id}`, credentials); }
      sessionStorage.setItem(`aceverse:${player.username}`, player.playerId); setSession({ credentials, player }); tell(`Welcome ${player.username}.`);
    } catch (error) { tell(error.message, true); } finally { setBusy(false); }
  }
  return <section className="panel auth-panel"><p className="eyebrow">Teen Patti - virtual coins only</p><h1>ACEVERSE</h1><div className="tabs"><button className={!register ? "selected" : ""} onClick={() => setRegister(false)}>Sign in</button><button className={register ? "selected" : ""} onClick={() => setRegister(true)}>Register</button></div><form className="form-grid" onSubmit={submit}><label>Username<input minLength="3" value={form.username} onChange={update("username")} required /></label>{register && <label>Email<input type="email" value={form.email} onChange={update("email")} required /></label>}<label>Password<input type="password" minLength="8" value={form.password} onChange={update("password")} required /></label><button className="primary wide" disabled={busy}>{register ? "Create player" : "Enter lobby"}</button></form></section>;
}

function Lobby({ session, table, setTable, start, signOut, tell }) {
  const [name, setName] = useState(`${session.player.username}'s table`); const [bet, setBet] = useState(100); const [max, setMax] = useState(4); const [tableId, setTableId] = useState(""); const [busy, setBusy] = useState(false);
  async function create(event) { event.preventDefault(); setBusy(true); try { setTable(await api("/tables", session.credentials, "POST", { hostPlayerId: session.player.playerId, tableName: name, entryBet: Number(bet), maxPlayers: Number(max) })); } catch (error) { tell(error.message, true); } finally { setBusy(false); } }
  async function join(event) { event.preventDefault(); setBusy(true); try { setTable(await api(`/tables/${tableId}/players`, session.credentials, "POST", { playerId: session.player.playerId })); } catch (error) { tell(error.message, true); } finally { setBusy(false); } }
  if (!table) return <section className="lobby-grid"><form className="panel form-grid" onSubmit={create}><p className="eyebrow">Host a table</p><h2>Create game</h2><label>Table name<input value={name} onChange={(e) => setName(e.target.value)} required /></label><label>Starting bet<input type="number" min="1" value={bet} onChange={(e) => setBet(e.target.value)} required /></label><label>Maximum players<select value={max} onChange={(e) => setMax(e.target.value)}>{[2, 3, 4, 5, 6, 7, 8].map((n) => <option key={n}>{n}</option>)}</select></label><button className="primary" disabled={busy}>Create</button></form><form className="panel form-grid" onSubmit={join}><p className="eyebrow">Join friends</p><h2>Enter table ID</h2><label>Table ID<input type="number" min="1" value={tableId} onChange={(e) => setTableId(e.target.value)} required /></label><button className="secondary" disabled={busy}>Join table</button></form></section>;
  const host = table.hostPlayerId === session.player.playerId;
  return <section className="panel table-lobby"><div className="table-heading"><div><p className="eyebrow">Table #{table.tableId} - starting bet {table.entryBet}</p><h2>{table.tableName}</h2></div><span className={`status ${table.status.toLowerCase()}`}>{table.status}</span></div><p className="muted">Share this table ID. Each new player receives 10,000 virtual coins.</p><div className="seat-list">{table.players.map((p) => <div className="seat" key={p.playerId}><span className="seat-number">{p.seatNumber}</span>{p.username}{p.playerId === table.hostPlayerId && <em>Host</em>}</div>)}</div><div className="actions">{host && <button className="primary" disabled={table.players.length < 2 || busy} onClick={start}>{table.players.length < 2 ? "Waiting for player" : "Deal cards"}</button>}<button className="secondary" onClick={async () => { try { setTable(await api(`/tables/${table.tableId}`, session.credentials)); } catch (e) { tell(e.message, true); } }}>Refresh</button><button className="text-button" onClick={signOut}>Sign out</button></div></section>;
}

function Table({ session, table, round, hand, showdown, live, run, leaveRound, playAgain }) {
  const mine = round.players?.find((p) => p.playerId === session.player.playerId); const myTurn = round.currentTurnPlayerId === session.player.playerId; const [raise, setRaise] = useState(round.currentBet + 1); const [target, setTarget] = useState("");
  const players = showdown?.hands || round.players || []; const targets = (round.players || []).filter((p) => p.status === "ACTIVE" && p.playerId !== session.player.playerId);
  return <section className="game-board"><header className="game-header"><div><p className="eyebrow">Round {round.roundNumber} - pot {round.pot} - bet {round.currentBet}</p><h2>{table.tableName}</h2></div><div className="live-status"><span className={live ? "live-dot connected" : "live-dot"} />{live ? "LIVE" : "RECONNECTING"}</div></header>
    {!showdown && <div className="round-message">{round.phase === "CHOOSING_VISIBILITY" ? "Choose Blind or Seen. After 30 seconds unselected players become Blind." : round.phase === "FORCED_SAME" ? `Rejected Side Show: SAME only, ${round.forcedSameTurnsRemaining} turns remaining.` : myTurn ? "Your turn. The server will auto-drop you after 30 seconds." : "Waiting for the current player's action."}</div>}
    <div className="players-grid">{players.map((p) => { const own = p.playerId === session.player.playerId; const cards = showdown ? p.cards || [] : own ? hand?.cards || [] : [1, 2, 3]; return <article className={`player-hand ${showdown?.winnerPlayerId === p.playerId ? "winner" : ""}`} key={p.playerId}><div className="player-name">{p.username}{own && " (you)"}</div><div className="cards">{cards.map((c, i) => <Card key={c.position || i} card={c} hidden={!showdown && !own} />)}</div><div className="category">{showdown ? p.handCategory?.replaceAll("_", " ") : `${p.visibility} - ${p.status}`}</div></article>; })}</div>
    {!showdown && mine?.visibility === "PENDING" && <div className="actions centered"><button className="primary" onClick={() => run(`/rounds/${round.roundId}/visibility`, { choice: "BLIND" })}>Play Blind</button><button className="secondary" onClick={() => run(`/rounds/${round.roundId}/visibility`, { choice: "SEEN" })}>See Cards</button></div>}
    {!showdown && mine?.visibility === "BLIND" && <div className="actions centered"><button className="secondary" onClick={() => run(`/rounds/${round.roundId}/see-cards`)}>See my cards</button></div>}
    {!showdown && myTurn && ["BETTING", "FORCED_SAME"].includes(round.phase) && <div className="actions centered"><button className="primary" onClick={() => run(`/rounds/${round.roundId}/actions`, { action: "SAME" })}>Same {round.currentBet}</button>{round.phase === "BETTING" && <><input className="raise-input" type="number" min={round.currentBet + 1} value={raise} onChange={(e) => setRaise(e.target.value)} /><button className="secondary" onClick={() => run(`/rounds/${round.roundId}/actions`, { action: "RAISE", amount: Number(raise) })}>Raise</button><select value={target} onChange={(e) => setTarget(e.target.value)}><option value="">Side Show player</option>{targets.map((p) => <option key={p.playerId} value={p.playerId}>{p.username}</option>)}</select><button className="secondary" disabled={!target} onClick={() => run(`/rounds/${round.roundId}/side-shows`, { targetPlayerId: Number(target) })}>Side Show</button></>}<button className="text-button" onClick={leaveRound}>Drop</button></div>}
    {!showdown && round.phase === "SIDE_SHOW_PENDING" && round.pendingSideShowTargetPlayerId === session.player.playerId && <div className="actions centered"><button className="primary" onClick={() => run(`/rounds/${round.roundId}/side-shows/${round.pendingSideShowId}/response`, { response: "ACCEPT" })}>Accept Side Show</button><button className="secondary" onClick={() => run(`/rounds/${round.roundId}/side-shows/${round.pendingSideShowId}/response`, { response: "REJECT" })}>Reject</button></div>}
    {!showdown && mine?.status === "ACTIVE" && !myTurn && <div className="actions centered"><button className="text-button" onClick={leaveRound}>Leave game / Drop</button></div>}
    {showdown && <div className="round-message">{showdown.winnerUsername} wins: {showdown.winningHandCategory.replaceAll("_", " ")}</div>}{showdown && table.hostPlayerId === session.player.playerId && <div className="actions centered"><button className="primary" onClick={playAgain}>Play again</button></div>}
  </section>;
}

export default function Game() {
  const [session, setSession] = useState(null); const [table, setTable] = useState(null); const [round, setRound] = useState(null); const [hand, setHand] = useState(null); const [showdown, setShowdown] = useState(null); const [live, setLive] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const tell = useCallback((text, isError = false) => { setError(isError ? text : ""); setNotice(isError ? "" : text); }, []);
  const refreshTable = useCallback(async (id, credentials) => setTable(await api(`/tables/${id}`, credentials)), []);
  useEffect(() => { if (!session || !table?.tableId) return; const client = new Client({ brokerURL: wsUrl(), reconnectDelay: 3000, debug: () => {}, onConnect: () => { setLive(true); client.subscribe(`/topic/tables/${table.tableId}`, async (message) => { const event = JSON.parse(message.body); try { if (event.type === "SHOWDOWN") { setShowdown(event.showdown); await refreshTable(table.tableId, session.credentials); } else if (event.round) { setRound(event.round); setShowdown(null); setHand(null); await refreshTable(table.tableId, session.credentials); } else await refreshTable(table.tableId, session.credentials); } catch (e) { tell(e.message, true); } }); }, onWebSocketClose: () => setLive(false) }); client.activate(); return () => { setLive(false); client.deactivate(); }; }, [session, table?.tableId, refreshTable, tell]);
  useEffect(() => { const mine = round?.players?.find((p) => p.playerId === session?.player?.playerId); if (!round || !session || hand || mine?.visibility !== "SEEN") return; api(`/rounds/${round.roundId}/players/${session.player.playerId}/hand`, session.credentials).then(setHand).catch((e) => tell(e.message, true)); }, [round, session, hand, tell]);
  async function start() { try { const next = await api(`/tables/${table.tableId}/rounds`, session.credentials, "POST", { hostPlayerId: session.player.playerId }); setRound(next); setHand(null); setShowdown(null); } catch (e) { tell(e.message, true); } }
  async function run(path, body) { try { const next = await api(path, session.credentials, "POST", body); setRound(next); } catch (e) { tell(e.message, true); } }
  function signOut() { setSession(null); setTable(null); setRound(null); setHand(null); setShowdown(null); }
  return <main className="app-shell"><header className="brand">ACEVERSE <small>Authoritative Teen Patti</small>{session && <span className="identity">{session.player.username} - {session.player.coinBalance} coins</span>}</header><Message error={error} notice={notice} />{!session ? <Auth setSession={setSession} tell={tell} /> : !round ? <Lobby session={session} table={table} setTable={setTable} start={start} signOut={signOut} tell={tell} /> : <Table session={session} table={table} round={round} hand={hand} showdown={showdown} live={live} run={run} leaveRound={() => run(`/rounds/${round.roundId}/leave`)} playAgain={() => { setRound(null); setHand(null); setShowdown(null); }} />}</main>;
}
